allowBuilds:
  '@clerk/shared': true
  core-js: false
  esbuild: true
  msw: false
  protobufjs: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - msw
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@clerk/shared'
